const codeIATA =
    [
        { "AAE": "Annaba, Algeria - Les Salines" },
        { "AAL": "Aalborg, Denmark - Aalborg" },
        { "AAR": "Aarhus, Denmark - Tirstrup" },
        { "ABE": "Allentown, PA, USA - Allentown-Bethlehem-Easton Airport" },
        { "ABI": "Abilene, TX, USA - Municipal" },
        { "ABJ": "Abidjan, Cote D’ivoire - Port Bouet" },
        { "ABL": "Ambler, AK, USA" },
        { "ABM": "Bamaga, Queensland, Australia" },
        { "ABQ": "Albuquerque, NM, USA - Albuquerque International Airport" },
        { "ABR": "Aberdeen, SD, USA - Aberdeen Regional Airport" },
        { "ABS": "Abu Simbel, Egypt - Abu Simbel" },
        { "ABX": "Albury, New South Wales, Australia - Albury" },
        { "ABY": "Albany, GA, USA - Dougherty County" },
        { "ABZ": "Aberdeen, Scotland, United Kingdom - Dyce" },
        { "ACA": "Acapulco, Guerrero, Mexico - Alvarez International" },
        { "ACC": "Accra, Ghana - Kotoka" },
        { "ACE": "Lanzarote, Canary Islands, Spain - Lanzarote" },
        { "ACI": "Alderney, Channel Islands, United Kingdom - The Blaye" },
        { "ACK": "Nantucket, MA, USA" },
        { "ACT": "Waco, TX, USA - Madison Cooper" },
        { "ACV": "Arcata, CA, USA - Arcata/Eureka Airport" },
        { "ACY": "Atlantic City /Atlantic Cty, NJ, USA - Atlantic City International" },
        { "ADA": "Adana, Turkey - Adana" },
        { "ADB": "Izmir, Turkey - Adnam MenderesE" },
        { "ADD": "Addis Ababa, Ethiopia - Bole" },
        { "ADJ": "Amman, Jordan - Civil" },
        { "ADL": "Adelaide, South Australia, Australia - Adelaide" },
        { "ADQ": "Kodiak, AK, USA" },
        { "ADZ": "San Andres Island, Colombia" },
        { "AEP": "Buenos Aires, Buenos Aires, Argentina - Jorge Newbery" },
        { "AES": "Aalesund, Norway - Vigra" },
        { "AET": "Allakaket, AK, USA" },
        { "AEX": "Alexandria, LA, USA - Alexandria Intl Airport" },
        { "AEY": "Akureyri, Iceland - Akureyri" },
        { "AGA": "Agadir, Morocco - Inezgane" },
        { "AGB": "Augsburg, Germany - Muehlhausen" },
        { "AGF": "Agen, France - La Garenne" },
        { "AGH": "Helsingborg, Sweden - Angelholm/Helsingborg" },
        { "AGP": "Malaga, Spain - Malaga" },
        { "AGR": "Agra, India - Kheria" },
        { "AGS": "Augusta, GA, USA - Bush Field" },
        { "AGU": "Aguascalientes, Aguascalientes, Mexico" },
        { "AHN": "Athens, GA, USA" },
        { "AHO": "Alghero, Sardinia, Italy - Fertilia" },
        { "AIA": "Alliance, NE, USA" },
        { "AIN": "Wainwright, AK, USA" },
        { "AJN": "Anjouan, Comoros" },
        { "AJA": "Ajaccio, Corsica, France - Campo Dell Oro" },
        { "AJU": "Aracaju, Sergipe, Brazil" },
        { "AKJ": "Asahikawa, Japan - Asahikawa" },
        { "AKL": "Auckland, New Zealand - Auckland International Airport" },
        { "ALA": "Almaty, Kazakhstan - Almaty" },
        { "ALB": "Albany, NY, USA - Albany County Airport" },
        { "ALC": "Alicante, Spain - Alicante" },
        { "ALE": "Alpine, TX, USA - Alpine Texas" },
        { "ALF": "Alta, Norway - Elvebakken" },
        { "ALG": "Algiers, Algeria - Houari Boumedienne" },
        { "ALM": "Alamogordo, NM, USA" },
        { "ALO": "Waterloo, IA, USA - Waterloo Municipal Airport" },
        { "ALP": "Aleppo, Syria - Nejrab" },
        { "ALS": "Alamosa, CO, USA - Bergman Field" },

        { "FKL": "Franklin, PA, USA - Chess Lamberton" },
        { "FLG": "Flagstaff, AZ, USA - Flagstaff" },
        { "FLL": "Ft Lauderdale, FL, USA - Ft Lauderdale/Hollywood Intl Apt" },
        { "FLN": "Florianopolis, Santa Catarina, Brazil - Florianopolis" },
        { "FLO": "Florence, SC, USA - Gilbert Field" },
        { "FLR": "Florence, Italy" },
        { "FMA": "Formosa, Formosa, Argentina - Formosa" },
        { "FMN": "Farmington, NM, USA - Four Corners Regional Airport" },
        { "FMO": "Muenster, Germany - Muenster" },
        { "FNC": "Funchal, Madeira Islands, Portugal - Funchal" },
        { "FNL": "Fort Collins/Loveland, CO, USA - Fort Collins / Loveland Airport" },
        { "FNT": "Flint, MI, USA - Bishop Int’l Airport" },
        { "FOD": "Fort Dodge, IA, USA - Fort Dodge Regional Airport" },
        { "FOE": "Topeka, KS, USA - Forbes Field" },
        { "FOR": "Fortaleza, Ceara, Brazil - Fortaleza" },
        { "FPO": "Freeport, Bahamas - Freeport Intl Airport" },
        { "FRA": "Frankfurt, Germany - Frankfurt International" },
        { "FRD": "Friday Harbor, WA, USA - Friday Harbor Airport" },
        { "FRM": "Fairmont, MN, USA - Fairmont Municipal" },
        { "FRO": "Floro, Norway - Floro" },
        { "FRS": "Flores, Guatemala - Flores" },
        { "FRU": "Bishkek, Kyrgyzstan - Bishkek Airport" },
        { "FSD": "Sioux Falls, SD, USA - Joe Foss Field" },
        { "FSM": "Fort Smith, AR, USA - Fort Smith Municipal" },
        { "FSP": "St Pierre, St. Pierre And Miquelon" },
        { "FUE": "Fuerteventura / Puerto Del Rosario, Canary Islands Spain" },
        { "FUK": "Fukuoka, Japan - Itazuke" },
        { "FWA": "Fort Wayne, IN, USA - Baer Field" },
        { "FYV": "Fayetteville, AR, USA - Municipal" },
        { "GAJ": "Yamagata, Japan - Junmachi" },
        { "GAL": "Galena, AK, USA" },
        { "GAU": "Gauhati, India - Borjhar" },
        { "GBE": "Gaborone, Botswana - Gaborone" },
        { "GBG": "Galesburg, IL, USA - Galesburg Municiple Airport" },
        { "GCC": "Gillette, WY, USA - Campbell County Airport" },
        { "GCI": "Guernsey, Channel Islands, United Kingdom - Guernsey" },
        { "GCK": "Garden City, KS, USA - Garden City Municipal Airport" },
        { "GCM": "Grand Cayman Island, Cayman Islands - Owen Roberts Intl Airport" },
        { "GCN": "Grand Canyon, AZ, USA" },
        { "GDL": "Guadalajara, Jalisco, Mexico - Miguel Hidalgo Intl" },
        { "GDN": "Gdansk, Poland - Rebiechowo" },
        { "GDT": "Grand Turk Is, Turks And Caicos Islands" },
        { "GDV": "Glendive, MT, USA" },
        { "GDX": "Magadan, Russia - Magadan" },
        { "GEG": "Spokane, WA, USA - International/Geiger Field" },
        { "GEN": "Oslo, Norway - Garderm O E N" },
        { "GEO": "Georgetown, Guyana - Timehri" },
        { "GET": "Geraldton, Western Australia, Australia - Geraldton" },
        { "GFK": "Grand Forks, ND, USA - Grand Forks International Airport" },
        { "GGG": "Longview/Gladewater/Kilgore, TX, USA - Gregg County" },
        { "GGT": "George Town, Bahamas - Exuma International" },
        { "GGW": "Glasgow, MT, USA" },
        { "GHB": "Governors Harbour, Bahamas" },
        { "GIB": "Gibraltar, Gibraltar - Gibraltar" },
        { "GIG": "Rio De Janeiro, Rio De Janeiro, Brazil - International Airport" },
        { "GJT": "Grand Junction, CO, USA - Walker Field" },
        { "GKA": "Goroka, Papua New Guinea - Goroka" },
        { "GLA": "Glasgow, Scotland, United Kingdom - Glasgow Scotland" },
        { "GLD": "Goodland, KS, USA - Renner Field" },
        { "GLF": "Golfito, Costa Rica - Golfito" },
        { "GLS": "Galveston, TX, USA - Scholes Field" },
        { "GLV": "Golovin, AK, USA" },

        { "BBK": "Kasane, Botswana - Kasane" },
        { "BBU": "Bucharest, Romania - Baneasa" },
        { "BCD": "Bacolod, Philippines - Bacolod" },
        { "BCN": "Barcelona, Spain - Barcelona" },
        { "BDA": "Bermuda/Hamilton, Bermuda - Kindley Airfield/Civil Air Terminal" },
        { "BDJ": "Banjarmasin, Indonesia - Syamsudin Noor" },
        { "BDL": "Hartford, CT, USA - Bradley International Airport" },
        { "BDO": "Bandung, Indonesia - Husein Sastranegara" },
        { "BDQ": "Vadodara, India - Vadodara" },
        { "BDR": "Bridgeport, CT, USA - Sikorsky Memorial" },
        { "BED": "Bedford, MA, USA - Bedford" },
        { "BEG": "Belgrade, Yugoslavia - Belgrade-Beograd" },
        { "BEH": "Benton Harbor, MI, USA - Ross Field" },
        { "BEI": "Beica, Ethiopia - Beica" },
        { "BEL": "Belem, Para, Brazil - Val De Cans" },
        { "BEO": "Newcastle, New South Wales, Australia - Belmont" },
        { "BER": "Berlin, Germany - Schoenefeld" },
        { "BES": "Brest, France - Guipavas" },
        { "BET": "Bethel, AK, USA - Bethel" },
        { "BEW": "Beira, Mozambique - Beira" },
        { "BEY": "Beirut, Lebanon - International" },
        { "BFD": "Bradford, PA, USA - Bradford Regional" },
        { "BFF": "Scottsbluff, NE, USA - William B Heiling Field" },
        { "BFL": "Bakersfield, CA, USA - Meadows Field" },
        { "BFN": "Bloemfontein, South Africa - Jbm Hertzog" },
        { "BFS": "Belfast, Northern Ireland, United Kingdom - Belfast International" },
        { "BGA": "Bucaramanga, Colombia - Palo Negro" },
        { "BGF": "Bangui, Central African Republic - Bangui" },
        { "BGI": "Bridgetown, Barbados - Grantley Adams International" },
        { "BGK": "Big Creek, Belize - Big Creek" },
        { "BGM": "Binghamton/Endicott/Johnson City, NY, USA - Edwin Alink Field" },
        { "BGO": "Bergen, Norway - Flesland" },
        { "BGR": "Bangor, ME, USA - Bangor International Airport" },
        { "BGY": "Milan, Italy - Orio Al Serio" },
        { "BHB": "Bar Harbor, ME, USA" },
        { "BHD": "Belfast, Northern Ireland, United Kingdom - Belfast Harbor" },
        { "BHI": "Bahia Blanca, Buenos Aires, Argentina - Commandante" },
        { "BHK": "Bukhara, Uzbekistan" },
        { "BHM": "Birmingham, AL, USA - Seibels/Bryan Airport" },
        { "BHQ": "Broken Hill, New South Wales, Australia - Broken Hill" },
        { "BHS": "Bathurst, New South Wales, Australia - Raglan" },
        { "BHX": "Birmingham, England, United Kingdom - International" },
        { "BIA": "Bastia, Corsica, France - Poretta" },
        { "BIK": "Biak, Indonesia - Mokmer" },
        { "BIL": "Billings, MT, USA - Billings Logan Intnl Airport" },
        { "BIM": "Bimini, Bahamas - Bimini Island International" },
        { "BIO": "Bilbao, Spain - Sondica" },
        { "BIQ": "Biarritz, France - Parme" },
        { "BIS": "Bismarck, ND, USA - Bismarck Mannan Municipal" },
        { "BJI": "Bemidji, MN, USA - Bemidji Municipal Airport" },
        { "BJL": "Banjul, Gambia - Yundum International" },
        { "BJX": "Leon/Guanajuato, Guanajuato, Mexico - Del Bajio" },
        { "BKI": "Kota Kinabalu, Sabah, Malaysia - Kota Kinabalu" },
        { "BKK": "Bangkok, Thailand - Bangkok International Airport" },
        { "BKO": "Bamako, Mali - Senou" },
        { "BKW": "Beckley, WV, USA" },
        { "BKX": "Brookings, SD, USA - Brookings Municipal Airport" },
        { "BLA": "Barcelona, Venezuela - Gral Jose Antonio Anzoategui" },
        { "BLF": "Bluefield, WV, USA" },
        { "BLI": "Bellingham, WA, USA - Bellingham International" },
        { "BLK": "Blackpool, England, United Kingdom - Blackpool" },
        { "BLL": "Billund, Denmark - Billund" },

        { "BLQ": "Bologna, Italy - Guglielmo Marconi" },
        { "BLR": "Bangalore, India - Hindustan" },
        { "BLZ": "Blantyre, Malawi - Chileka" },
        { "BMA": "Stockholm, Sweden - Bromma Arpt" },
        { "BMG": "Bloomington, IN, USA - Monroe County Airport" },
        { "BMI": "Bloomington, IL, USA - Normal" },
        { "BNA": "Nashville, TN, USA - Nashville Metropolitan Airport" },
        { "BNE": "Brisbane, Queensland, Australia - Brisbane International Airport" },
        { "BNJ": "Bonn, Germany - Train Main Railroad Station" },
        { "BNN": "Bronnoysund, Norway - Bronnoy" },
        { "BNS": "Barinas, Venezuela - Barinas" },
        { "BOD": "Bordeaux, France - Merignac" },
        { "BOG": "Bogota, Colombia - Eldorado" },
        { "BOI": "Boise, ID, USA - Boise Municipal Arpt (Gowen Field)" },
        { "BOM": "Bombay, India - Bombay" },
        { "BON": "Bonaire, Netherlands Antilles - Flamingo Field" },
        { "BOO": "Bodo, Norway - Bodo" },
        { "BOS": "Boston, MA, USA - Logan International Airport" },
        { "BPS": "Porto Seguro, Bahia, Brazil - Porto Seguro" },
        { "BPT": "Beaumont, TX, USA - Jefferson County" },
        { "BQK": "Brunswick, GA, USA - Glynco Jetport" },
        { "BQN": "Aguadilla, PR, USA" },
        { "BRC": "San Carlos De Bariloche, Rio Negro, Argentina - International" },
        { "BRD": "Brainerd, MN, USA" },
        { "BRE": "Bremen, Germany - Bremen" },
        { "BRI": "Bari, Italy" },
        { "BRL": "Burlington, IA, USA - Burlington Municipal Airport" },
        { "BRM": "Barquisimeto, Venezuela - Barquisimeto" },
        { "BRN": "Berne, Switzerland - Belp" },
        { "BRO": "Brownsville, TX, USA - South Padre Island Intl" },
        { "BRQ": "Brno, Czech Republic - Turany" },
        { "BRR": "Barra / Hebrides Islands, Scotland, United Kingdom - North Bay" },
        { "BRS": "Bristol, England, United Kingdom - Bristol" },
        { "BRT": "Bathurst Island, Northern Territory, Australia" },
        { "BRU": "Brussels, Belgium - National" },
        { "BRW": "Barrow, AK, USA - Barrow" },
        { "BSB": "Brasilia, Distrito Federal, Brazil - International" },
        { "BSK": "Biskra, Algeria - Biskra" },
        { "BSL": "Basel, Switzerland - Basel" },
        { "BTM": "Butte, MT, USA" },
        { "BTS": "Bratislava, Slovakia - Ivanka" },
        { "BTU": "Bintulu, Sarawak, Malaysia - Bintulu" },
        { "BTV": "Burlington, VT, USA - Burlington International Airport" },
        { "BUD": "Budapest, Hungary - Ferihegy" },
        { "BUF": "Buffalo, NY, USA - Greater Buffalo Intl Airport" },
        { "BUQ": "Bulawayo, Zimbabwe - Bulawayo" },
        { "BUR": "Burbank, CA, USA - Burbank Glendale Pasadena Airport" },
        { "BUZ": "Bushehr, Iran - Bushehr" },
        { "BVB": "Boa Vista, Roraima, Brazil" },
        { "BVE": "Brive-La-Gaillarde, France - Laroche" },
        { "BVI": "Birdsville, Queensland, Australia - Birdsville" },
        { "BWA": "Bhairawa, Nepal - Bhairawa" },
        { "BWI": "Baltimore, MD, USA - Baltimore-Washington International" },
        { "BWN": "Bandar Seri Begawan, Brunei Darussalam - Brunei International" },
        { "BXN": "Bodrum, Turkey - Imsik Airport" },
        { "BXU": "Butuan, Philippines - Butuan" },
        { "BYU": "Bayreuth, Germany - Bindlacher Berg" },
        { "BZE": "Belize City, Belize - Belize International" },
        { "BZN": "Bozeman, MT, USA - Gallatin Field" },
        { "BZR": "Beziers, France - Beziers-Vias" },
        { "CAE": "Columbia, SC, USA - Columbia Sc Airport Metropolitan" },
        { "CAG": "Cagliari, Sardinia, Italy - Elmas" },

        { "CAI": "Cairo, Egypt - International" },
        { "CAJ": "Canaima, Venezuela" },
        { "CAK": "Akron/Canton, OH, USA - Akron-Canton Regional Airport" },
        { "CAN": "Guangzhou, China - Baiyun" },
        { "CAS": "Casablanca, Morocco - Anfa" },
        { "CAY": "Cayenne, French Guiana - Rochambeau" },
        { "CBB": "Cochabamba, Bolivia - San Jose De La Banda" },
        { "CBE": "Cumberland, MD, USA - Municipal" },
        { "CBG": "Cambridge, England, United Kingdom - Cambridge" },
        { "CBL": "Ciudad Bolivar, Venezuela" },
        { "CBR": "Canberra, Australian Capital Territory, Australia - Canberra" },
        { "CCF": "Carcassonne, France - Salvaza Airport" },
        { "CCJ": "Calicut, India" },
        { "CCP": "Concepcion, Chile - Carriel Sur" },
        { "CCS": "Caracas, Venezuela - Simon Bolivar International" },
        { "CCU": "Calcutta, India - Calcutta" },
        { "CDC": "Cedar City, UT, USA" },
        { "CDG": "Paris, France - Charles De Gaulle" },
        { "CDH": "Camden, AR, USA" },
        { "CDR": "Chadron, NE, USA" },
        { "CDV": "Cordova, AK, USA" },
        { "CEB": "Cebu, Philippines - International" },
        { "CEC": "Crescent City, CA, USA - Crescent City Municipal Airport" },
        { "CEI": "Chiang Rai, Thailand - Chiang Rai" },
        { "CEN": "Ciudad Obregon, Sonora, Mexico" },
        { "CER": "Cherbourg, France - Maupertus" },
        { "CEZ": "Cortez, CO, USA - Montezuma County" },
        { "CFR": "Caen, France - Carpiquet" },
        { "CFU": "Kerkyra, Greece - Kerkyra" },
        { "CGA": "Craig, AK, USA" },
        { "CGB": "Cuiaba, Mato Grosso, Brazil" },
        { "CGH": "Sao Paulo, Sao Paulo, Brazil - Congonhas" },
        { "CGI": "Cape Girardeau, MO, USA - Municipal Airport" },
        { "CGK": "Jakarta, Indonesia - Soekarno Hatta International" },
        { "CGN": "Cologne/Bonn, Germany - Koeln/Bonn" },
        { "CGO": "Zhengzhou, China" },
        { "CGP": "Chittagong, Bangladesh - Patenga" },
        { "CGQ": "Changchun, China" },
        { "CGR": "Campo Grande, Mato Grosso Do Sul, Brazil" },
        { "CGX": "Chicago, IL, USA - Meigs Field" },
        { "CGX": "Chicago, IL, USA - Midway / Ohare / Meigs" },
        { "CHA": "Chattanooga, TN, USA - Cha Lovell Field" },
        { "CHC": "Christchurch, New Zealand - International" },
        { "CHO": "Charlottesville, VA, USA - Charlottesville/Albemarle" },
        { "CHQ": "Chania, Crete Island, Greece - Souda" },
        { "CHS": "Charleston, SC, USA - Charleston International Airport" },
        { "CIA": "Rome, Italy - Ciampino" },
        { "CIC": "Chico, CA, USA - Chico Municipal Air Terminal" },
        { "CID": "Cedar Rapids, IA, USA - Municipal" },
        { "CIU": "Sault Ste Marie, MI, USA - Chippewa County Intl Airport" },
        { "CIX": "Chiclayo, Peru - Cornel Ruiz" },
        { "CJB": "Coimbatore, India - Peelamedu" },
        { "CJS": "Ciudad Juarez, Chihuahua, Mexico - International Abraham Gonzalez" },
        { "CJU": "Cheju, South Korea - Cheju" },
        { "CKB": "Clarksburg, WV, USA - Clarksburg-Benedum Airport" },
        { "CKS": "Carajas, Para, Brazil - International / Brasilia Brazil" },
        { "CKY": "Conakry, Guinea - Conakry" },
        { "CLD": "Carlsbad, CA, USA - Carlsbad/Palomar Airport" },
        { "CLE": "Cleveland, OH, USA - Hopkins International Airport" },
        { "CLJ": "Cluj, Romania - Cluj" },
        { "CLL": "College Station, TX, USA" },
        { "CLM": "Port Angeles, WA, USA - Wm Fairchild Intl Airport" },

        { "CLO": "Cali, Colombia - Alfonso Bonilla Aragon" },
        { "CLQ": "Colima, Colima, Mexico" },
        { "CLT": "Charlotte, NC, USA - Charlotte/Douglas Intl Airport" },
        { "CLY": "Calvi, Corsica, France - Ste Catherine" },
        { "CMB": "Colombo, Sri Lanka - Katunayake International" },
        { "CME": "Ciudad Del Carmen, Campeche, Mexico" },
        { "CMF": "Chambery, France - Chambery Aix-Les-Bains" },
        { "CMG": "Corumba, Mato Grosso Do Sul, Brazil - Corumba" },
        { "CMH": "Columbus OH, USA - Port Columbus Intl Airport" },
        { "CMI": "Champaign, IL, USA - Univ Of Illinois-Willard Airport" },
        { "CMN": "Casablanca, Morocco - Mohamed V" },
        { "CMX": "Hancock, MI, USA - Houghton County / Memorial" },
        { "CND": "Constanta, Romania - Kogalniceanu" },
        { "CNF": "Belo Horizonte /Belo Horizon, Minas Gerais, Brazil - Aeropuerto Internacional Tancredo Neves" },
        { "CNM": "Carlsbad, NM, USA" },
        { "CNS": "Cairns, Queensland, Australia - Cairns" },
        { "CNX": "Chiang Mai, Thailand - International" },
        { "CNY": "Moab, UT, USA" },
        { "COK": "Cochin, India - Naval Air Station" },
        { "COO": "Cotonou, Benin - Cotonou" },
        { "COR": "Cordoba, Cordoba, Argentina - Pajas Blancas" },
        { "COS": "Colorado Springs, CO, USA - Colorado Springs Municipal" },
        { "COU": "Columbia, MO, USA - Columbia Regional" },
        { "CPC": "San Martin De Los Andes, Neuquen, Argentina" },
        { "CPH": "Copenhagen, Denmark - Copenhagen" },
        { "CPQ": "Campinas, Sao Paulo, Brazil - Campinas International" },
        { "CPR": "Casper, WY, USA - Natrona County Intl Airport" },
        { "CPT": "Cape Town, South Africa - D F Malan" },
        { "CRD": "Comodoro Rivadavia, Chubut, Argentina - Comodoro Chubut, Argentina - Comodoro Rivadavia" },
        { "CRI": "Crooked Island, Bahamas" },
        { "CRP": "Corpus Christi, TX, USA - Corpus Christi International Airport" },
        { "CRU": "Carriacou Island, Grenada" },
        { "CRW": "Charleston, WV, USA - Yeager Airport" },
        { "CSG": "Columbus, GA, USA - Columbus Metropolitan / Fort Benning" },
        { "CSX": "Changsha, China" },
        { "CTA": "Catania, Sicily, Italy - Fontanarossa" },
        { "CTG": "Cartagena, Colombia - Rafael Nunez" },
        { "CTL": "Charleville, Queensland, Australia - Charleville" },
        { "CTS": "Sapporo, Japan - Chitose" },
        { "CTU": "Chengdu, China" },
        { "CUC": "Cucuta, Colombia - Camilo Daza" },
        { "CUE": "Cuenca, Ecuador - Mariscal La Mar" },
        { "CUL": "Culiacan, Sinaloa, Mexico" },
        { "CUM": "Cumana, Venezuela" },
        { "CUN": "Cancun, Mexico" },
        { "CUP": "Carupano, Venezuela - Carupano" },
        { "CUR": "Willemstad / Curacao Island, Netherlands Antilles - Areopuerto Hato" },
        { "CUU": "Chihuahua, Chihuahua, Mexico - Genvillalobos" },
        { "CUZ": "Cuzco, Peru - Tte Velazco Astete" },
        { "CVG": "Cincinnati, OH, USA - Greater Cincinnati Intl Airport" },
        { "CVN": "Clovis, NM, USA" },
        { "CWA": "Wausau, WI, USA - Central Wisconsin Airport" },
        { "CWB": "Curitiba, Parana, Brazil - Afonso Pena" },
        { "CWL": "Cardiff, Wales, United Kingdom - Cardiff-Wales" },
        { "CWT": "Cowra, New South Wales, Australia - Cowra" },
        { "CXH": "Vancouver, British Columbia, Canada - Vancouver Harbour Airport" },
        { "CYB": "Cayman Brac Island, Cayman Islands" },
        { "CYR": "Colonia, Uruguay" },
        { "CYS": "Cheyenne, WY, USA - Cheyenne Municipal Airport" },
        { "CZM": "Cozumel, Quintana Roo, Mexico - Aeropuerto Intl De Cozumel" },
        { "DAB": "Daytona Beach, FL, USA - Daytona Beach International Airport" },

        { "DAC": "Dhaka, Bangladesh - Zia International Airport" },
        { "DAD": "Da Nang, Vietnam - Da Nang" },
        { "DAL": "Dallas, TX, USA - Love Field" },
        { "DAM": "Damascus, Syria - Damascus Intl" },
        { "DAN": "Danville, VA, USA" },
        { "DAR": "Dar Es Salaam, Tanzania - International" },
        { "DAY": "Dayton, OH, USA - James M Cox Dayton International" },
        { "DBO": "Dubbo, New South Wales, Australia - Dubbo" },
        { "DBQ": "Dubuque, IA, USA - Dubuque Municipal Airport" },
        { "DCA": "Washington, DC, USA - Washington National Airport" },
        { "DCF": "Dominica, Dominica - Cane Field" },
        { "DDC": "Dodge City, KS, USA - Dodge City Municipal" },
        { "DEC": "Decatur, IL, USA - Decatur Municiple Airport" },
        { "DEL": "Delhi, India - Delhi International Airport" },
        { "DEM": "Dembidollo, Ethiopia - Dembidollo" },
        { "DEN": "Denver, CO, USA - Denver International" },
        { "DFW": "Dallas/Ft Worth, TX, USA - Dallas Ft Worth International" },
        { "DGA": "Dangriga, Belize - Dangriga" },
        { "DGO": "Durango, Durango, Mexico - Gen Guadalupe Victoria" },
        { "DHA": "Dhahran, Saudi Arabia - Dhahran Intl" },
        { "DHN": "Dothan, AL, USA - Municipal" },
        { "DIB": "Dibrugarh, India - Chabua" },
        { "DIJ": "Dijon, France - Longvic" },
        { "DIL": "Dili, Indonesia - Comoro" },
        { "DIY": "Diyarbakir, Turkey - Diyarbakia" },
        { "DKR": "Dakar, Senegal - Yoff" },
        { "DLA": "Douala, Cameroon - Douala" },
        { "DLC": "Dalian, China" },
        { "DLH": "Duluth, MN, USA - Duluth International Airport" },
        { "DLM": "Dalaman, Turkey - Dalaman" },
        { "DME": "Moscow, Russia - Domodedovo" },
        { "DND": "Dundee, Scotland, United Kingdom - Dundee" },
        { "DNM": "Denham, Western Australia, Australia" },
        { "DNV": "Danville, IL, USA - Vermilion County Airport" },
        { "DOH": "Doha, Qatar - Doha" },
        { "DOK": "Donetsk, Ukraine - Donetsk" },
        { "DOL": "Deauville, France - Saint Gatien" },
        { "DOM": "Dominica, Dominica - Melville Hal-Dom" },
        { "DPL": "Dipolog, Philippines - Dipolog" },
        { "DPO": "Devonport, Tasmania, Australia - Devonport" },
        { "DPS": "Denpasar Bali, Indonesia - Ngurah Rai" },
        { "DRO": "Durango, CO, USA - Durango La Plata County Airport" },
        { "DRS": "Dresden, Germany - Dresden" },
        { "DRT": "Del Rio, TX, USA" },
        { "DRW": "Darwin, Northern Territory, Australia" },
        { "DSI": "Destin, FL, USA" },
        { "DSM": "Des Moines, IA, USA" },
        { "DTM": "Dortmund, Germany - Wickede" },
        { "DTW": "Detroit, MI, USA - Detroit Metropolitan Airport" },
        { "DUB": "Dublin, Ireland - Dublin" },
        { "DUD": "Dunedin, New Zealand - Momona" },
        { "DUJ": "Du Bois, PA, USA - Jefferson County" },
        { "DUQ": "Duncan / Quam, British Columbia, Canada - Quamichan Lake" },
        { "DUR": "Durban, South Africa - Louis Botha" },
        { "DUS": "Dusseldorf, Germany - Dusseldorf" },
        { "DUT": "Dutch Harbor, AK, USA - Dutch Harbor" },
        { "DVO": "Davao, Philippines - Mati" },
        { "DXB": "Dubai, United Arab Emirates - Dubai International Airport" },
        { "EAP": "Basel, Switzerland" },
        { "EAR": "Kearney, NE, USA - Kearney Municipal Airport" },
        { "EAS": "San Sebastian, Spain - Fuenterrabia" },
        { "EAT": "Wenatchee, WA, USA - Pangborn Memorial Field" },

        { "EAU": "Eau Claire, WI, USA - Eau Claire Municipal" },
        { "EBA": "Elba Island, Italy - Marina Di Campo" },
        { "EBB": "Entebbe/Kampala, Uganda - Entebbe" },
        { "EBJ": "Esbjerg, Denmark - Esbjerg" },
        { "EDI": "Edinburgh, Scotland, United Kingdom - Turnhouse" },
        { "EDR": "Edward River, Queensland, Australia - Edward River" },
        { "EEN": "Keene / Brattleboro, NH, USA - Dillant Hopkins" },
        { "EFD": "Houston, TX, USA - Ellington Field" },
        { "EGE": "Vail/Eagle, CO, USA - Eagle County Regional" },
        { "EIN": "Eindhoven, Netherlands - Welschap" },
        { "EIS": "Tortola/Beef Island, Virgin Islands (British) - Beef Island" },
        { "EJA": "Barrancabermeja, Colombia - Variguies" },
        { "EKO": "Elko, NV, USA - J C Harris Field" },
        { "ELD": "El Dorado, AR, USA" },
        { "ELH": "North Eleuthera, Bahamas" },
        { "ELM": "Elmira / Corning, NY, USA - Elmira Corning Regional Arpt" },
        { "ELP": "El Paso, TX, USA - El Paso International Airport" },
        { "ELS": "East London, South Africa - Ben Shoeman" },
        { "ELY": "Ely, NV, USA - Yelland Field" },
        { "EMA": "East Midlands, England, United Kingdom - East Midlands" },
        { "EMD": "Emerald, Queensland, Australia - Emerald" },
        { "ENA": "Kenai, AK, USA - Kenai Municipal Airport" },
        { "ENS": "Enschede, Netherlands - Twente" },
        { "EOH": "Medellin, Colombia - Enrique Olaya Herrara" },
        { "EPR": "Esperance, Western Australia, Australia - Esperance" },
        { "ERF": "Erfurt, Germany - Erfurt" },
        { "ERI": "Erie, PA, USA - Erie International" },
        { "ERS": "Windhoek, Namibia - Eros" },
        { "ERZ": "Erzurum, Turkey - Erzurum" },
        { "ESB": "Ankara, Turkey - Esenboga" },
        { "ESC": "Escanaba, MI, USA - Delta County Airport" },
        { "ESD": "Eastsound, WA, USA - Eastsound/Orcas Island Airport" },
        { "ESR": "El Salvador, Chile" },
        { "ETH": "Elat, Israel - Elat" },
        { "ETZ": "Metz/Nancy, France - Frescaty" },
        { "EUG": "Eugene, OR, USA - Eugene Airport" },
        { "EUN": "Laayoune, Morocco - Laayoune-Hassan I Morocco" },
        { "EVE": "Evenes, Norway - Evenes" },
        { "EVN": "Yerevan, Armenia" },
        { "EVV": "Evansville, IN, USA - Evansville Regional Airport" },
        { "EWB": "New Bedford/Fall River, MA, USA - New Bedford Municipal" },
        { "EWN": "New Bern, NC, USA - Simmons-Nott Airport" },
        { "EWR": "Newark, NJ, USA - Newark International Airport" },
        { "EXT": "Exeter, England, United Kingdom - Exeter" },
        { "EYW": "Key West, FL, USA" },
        { "EZE": "Buenos Aires, Argentina - Eze - Ezeiza International Airport" },
        { "FAE": "Faroe Islands, Faroe Islands - Faeroe Islands" },
        { "FAI": "Fairbanks, AK, USA - Fairbanks International Airport" },
        { "FAO": "Faro, Portugal - Faro" },
        { "FAR": "Fargo, ND, USA - Hector Airport" },
        { "FAT": "Fresno, CA, USA - Fresno Air Terminal" },
        { "FAY": "Fayetteville, NC, USA - Fayetteville Municipal" },
        { "FBU": "Oslo, Norway - Fornebu" },
        { "FCA": "Kalispell, MT, USA - Glacier Park International" },
        { "FCO": "Rome, Italy - Leonardo Da Vinci/Fiumicino" },
        { "FDE": "Forde, Norway - Forde" },
        { "FDF": "Fort De France, Martinique - Fort De France" },
        { "FDH": "Friedrichshafen, Germany - Friedrichshafen - Lowenthal" },
        { "FEZ": "Fez, Morocco - Fez" },
        { "FFM": "Fergus Falls, MN, USA - Fergus Falls Municipal Airport" },
        { "FHU": "Fort Huachuca/Sierra Vista, AZ, USA" },
        { "FIH": "Kinshasa, Zaire - Kinshasa" },

        { "FKL": "Franklin, PA, USA - Chess Lamberton" },
        { "FLG": "Flagstaff, AZ, USA - Flagstaff" },
        { "FLL": "Ft Lauderdale, FL, USA - Ft Lauderdale/Hollywood Intl Apt" },
        { "FLN": "Florianopolis, Santa Catarina, Brazil - Florianopolis" },
        { "FLO": "Florence, SC, USA - Gilbert Field" },
        { "FLR": "Florence, Italy" },
        { "FMA": "Formosa, Formosa, Argentina - Formosa" },
        { "FMN": "Farmington, NM, USA - Four Corners Regional Airport" },
        { "FMO": "Muenster, Germany - Muenster" },
        { "FNC": "Funchal, Madeira Islands, Portugal - Funchal" },
        { "FNL": "Fort Collins/Loveland, CO, USA - Fort Collins / Loveland Airport" },
        { "FNT": "Flint, MI, USA - Bishop Int’l Airport" },
        { "FOD": "Fort Dodge, IA, USA - Fort Dodge Regional Airport" },
        { "FOE": "Topeka, KS, USA - Forbes Field" },
        { "FOR": "Fortaleza, Ceara, Brazil - Fortaleza" },
        { "FPO": "Freeport, Bahamas - Freeport Intl Airport" },
        { "FRA": "Frankfurt, Germany - Frankfurt International" },
        { "FRD": "Friday Harbor, WA, USA - Friday Harbor Airport" },
        { "FRM": "Fairmont, MN, USA - Fairmont Municipal" },
        { "FRO": "Floro, Norway - Floro" },
        { "FRS": "Flores, Guatemala - Flores" },
        { "FRU": "Bishkek, Kyrgyzstan - Bishkek Airport" },
        { "FSD": "Sioux Falls, SD, USA - Joe Foss Field" },
        { "FSM": "Fort Smith, AR, USA - Fort Smith Municipal" },
        { "FSP": "St Pierre, St. Pierre And Miquelon" },
        { "FUE": "Fuerteventura / Puerto Del Rosario, Canary Islands Spain" },
        { "FUK": "Fukuoka, Japan - Itazuke" },
        { "FWA": "Fort Wayne, IN, USA - Baer Field" },
        { "FYV": "Fayetteville, AR, USA - Municipal" },
        { "GAJ": "Yamagata, Japan - Junmachi" },
        { "GAL": "Galena, AK, USA" },
        { "GAU": "Gauhati, India - Borjhar" },
        { "GBE": "Gaborone, Botswana - Gaborone" },
        { "GBG": "Galesburg, IL, USA - Galesburg Municiple Airport" },
        { "GCC": "Gillette, WY, USA - Campbell County Airport" },
        { "GCI": "Guernsey, Channel Islands, United Kingdom - Guernsey" },
        { "GCK": "Garden City, KS, USA - Garden City Municipal Airport" },
        { "GCM": "Grand Cayman Island, Cayman Islands - Owen Roberts Intl Airport" },
        { "GCN": "Grand Canyon, AZ, USA" },
        { "GDL": "Guadalajara, Jalisco, Mexico - Miguel Hidalgo Intl" },
        { "GDN": "Gdansk, Poland - Rebiechowo" },
        { "GDT": "Grand Turk Is, Turks And Caicos Islands" },
        { "GDV": "Glendive, MT, USA" },
        { "GDX": "Magadan, Russia - Magadan" },
        { "GEG": "Spokane, WA, USA - International/Geiger Field" },
        { "GEN": "Oslo, Norway - Garderm O E N" },
        { "GEO": "Georgetown, Guyana - Timehri" },
        { "GET": "Geraldton, Western Australia, Australia - Geraldton" },
        { "GFK": "Grand Forks, ND, USA - Grand Forks International Airport" },
        { "GGG": "Longview/Gladewater/Kilgore, TX, USA - Gregg County" },
        { "GGT": "George Town, Bahamas - Exuma International" },
        { "GGW": "Glasgow, MT, USA" },
        { "GHB": "Governors Harbour, Bahamas" },
        { "GIB": "Gibraltar, Gibraltar - Gibraltar" },
        { "GIG": "Rio De Janeiro, Rio De Janeiro, Brazil - International Airport" },
        { "GJT": "Grand Junction, CO, USA - Walker Field" },
        { "GKA": "Goroka, Papua New Guinea - Goroka" },
        { "GLA": "Glasgow, Scotland, United Kingdom - Glasgow Scotland" },
        { "GLD": "Goodland, KS, USA - Renner Field" },
        { "GLF": "Golfito, Costa Rica - Golfito" },
        { "GLS": "Galveston, TX, USA - Scholes Field" },
        { "GLV": "Golovin, AK, USA" },

        { "GNB": "Grenoble, France - St Geoirs" },
        { "GND": "St Georges/Grenada, Grenada - Pt Saline" },
        { "GNV": "Gainesville, FL, USA - Jr Alison Municipal" },
        { "GOA": "Genoa, Italy - Christoforo Colombo" },
        { "GOH": "Nuuk, Greenland" },
        { "GOI": "Goa, India - Dabolim" },
        { "GOJ": "Nizhniy Novgorod, Russia - Nizhniy" },
        { "GON": "Groton / New London, CT, USA - Groton-New London" },
        { "GOT": "Gothenburg, Sweden - Landvetter" },
        { "GOV": "Gove, Northern Territory, Australia - Nhulunbuy" },
        { "GPS": "Galapagos Islands, Ecuador - Baltra" },
        { "GPT": "Gulfport, MS, USA - Gulfport/Biloxi" },
        { "GRB": "Green Bay, WI, USA - Austin/Straybel Field" },
        { "GRI": "Grand Island, NE, USA - Central Nebraska Regional Airport" },
        { "GRJ": "George, South Africa - George" },
        { "GRO": "Gerona, Spain - Costa Brava" },
        { "GRQ": "Groningen, Netherlands - Eelde" },
        { "GRR": "Grand Rapids, MI, USA - Kent County International Airport" },
        { "GRU": "Sao Paulo, Sao Paulo, Brazil - Guarulhos" },
        { "GRX": "Granada, Spain - Granada" },
        { "GRZ": "Graz, Austria - Thalerhof" },
        { "GSO": "Greensboro / High Point, NC, USA - Piedmont Triad Intl Airport" },
        { "GTF": "Great Falls, MT, USA - Great Falls International" },
        { "GTO": "Gorontalo, Indonesia - Tolotio" },
        { "GTR": "Columbus, MS, USA - Golden" },
        { "GUA": "Guatemala City, Guatemala - La Aurora Intl Airport" },
        { "GUB": "Guerrero Negro, Baja California Sur, Mexico - Guerrero Negro Airport" },
        { "GUC": "Gunnison, CO, USA - Gunnison County Airport" },
        { "GUM": "Guam, Guam - Ab Wonpat Intl Airport" },
        { "GUP": "Gallup, NM, USA - Gallup Municipal" },
        { "GUR": "Alotau, Papua New Guinea - Gurney" },
        { "GVA": "Geneva, Switzerland - Geneva" },
        { "GWD": "Gwadar, Pakistan" },
        { "GWT": "Westerland, Germany - Westerland" },
        { "GWY": "Galway, Ireland - Carnmore" },
        { "GXQ": "Coyhaique, Chile - Teniente Vidal" },
        { "GYE": "Guayaquil, Ecuador - Simon Bolivar" },
        { "GYM": "Guaymas, Sonora, Mexico" },
        { "GYY": "Gary, IN, USA" },
        { "HAD": "Halmstad, Sweden - Halmstad" },
        { "HAG": "The Hague, Netherlands" },
        { "HAH": "Moroni (Hahaya), Comoros" },
        { "HAJ": "Hanover, Germany - Langenhagen" },
        { "HAK": "Haikou, China - Haikou" },
        { "HAM": "Hamburg, Germany - Fuhlsbuttel" },
        { "HAN": "Hanoi, Vietnam - Noibai Airport" },
        { "HAU": "Haugesund, Norway - Karmoy" },
        { "HAV": "Havana, Cuba - Jose Marti" },
        { "HBA": "Hobart, Tasmania, Australia - Hobart" },
        { "HDB": "Heidelberg, Germany" },
        { "HDN": "Hayden, CO, USA - Yampa Valley Regional Airport" },
        { "HDY": "Hat Yai, Thailand" },
        { "HEL": "Helsinki, Finland - Helsinki" },
        { "HER": "Heraklion, Crete Island, Greece - Heraklion" },
        { "HET": "Hohhot, China" },
        { "HFT": "Hammerfest, Norway" },
        { "HGH": "Hangzhou, China" },
        { "HGN": "Mae Hong Son, Thailand - Mae Hong Son" },
        { "HGR": "Hagerstown, MD, USA - Washington County Regional Airport" },
        { "HHH": "Hilton Head, SC, USA - Municipal" },
        { "HIB": "Hibbing / Chisholm, MN, USA - Hibbing-Chisholm" },

        { "HIJ": "Hiroshima, Japan - Hiroshima" },
        { "HIR": "Honiara/Guadalcanal, Solomon Islands - Henderson International" },
        { "HIS": "Hayman Island, Queensland, Australia - Hayman Island Airport" },
        { "HKD": "Hakodate, Japan - Hakodate" },
        { "HKG": "Hong Kong, Hong Kong" },
        { "HKK": "Hokitika, New Zealand - Hokitika" },
        { "HKN": "Hoskins, Papua New Guinea - Hoskins" },
        { "HKT": "Phuket, Thailand - Phuket" },
        { "HKY": "Hickory, NC, USA" },
        { "HLN": "Helena, MT, USA" },
        { "HLP": "Jakarta, Indonesia - Halim Perdana Kusama" },
        { "HLZ": "Hamilton, New Zealand - Hamilton" },
        { "HMA": "Malmo, Sweden - Malmo Harbour" },
        { "HMO": "Hermosillo, Sonora, Mexico - General Ignacio Pesqueira Garcia" },
        { "HNA": "Morioka, Japan - Hanamaki" },
        { "HNH": "Hoonah, AK, USA" },
        { "HNL": "Honolulu, HI, USA - Honolulu International" },
        { "HNS": "Haines, AK, USA" },
        { "HOB": "Hobbs, NM, USA - Lea County" },
        { "HOM": "Homer, AK, USA - Homer Airport" },
        { "HON": "Huron, SD, USA - Huron Regional Airport" },
        { "HOT": "Hot Springs, AR, USA - Memorial Field" },
        { "HOU": "Houston, TX, USA - Houston Hobby Airport" },
        { "HPB": "Hooper Bay, AK, USA" },
        { "HPN": "Westchester County, NY, USA - Westchester County Airport" },
        { "HPV": "Kauai Island, HI, USA - Princeville" },
        { "HRB": "Harbin, China - Harbin" },
        { "HRE": "Harare, Zimbabwe - Harare" },
        { "HRG": "Hurghada, Egypt - Hurghada" },
        { "HRK": "Kharkov, Ukraine - Kharkov" },
        { "HRL": "Harlingen, TX, USA - Harlingen" },
        { "HRO": "Harrison, AR, USA - Boone County" },
        { "HSI": "Hastings, NE, USA" },
        { "HSV": "Huntsville/Decatur, AL, USA - Huntsville-Madison County Jetplex" },
        { "HTI": "Hamilton Island, Queensland, Australia - Hamilton Island" },
        { "HTS": "Huntington / Ashland, WV, USA - Tri-State" },
        { "HUF": "Terre Haute, IN, USA - Hulman Field" },
        { "HUI": "Hue, Vietnam - Hue" },
        { "HUM": "Houma, LA, USA - Terrebonne" },
        { "HUN": "Hualien, Taiwan - Hualien" },
        { "HUX": "Huatulco, Oaxaca, Mexico - Huatulco" },
        { "HUY": "Humberside, England, United Kingdom - Humberside" },
        { "HVB": "Hervey Bay, Queensland, Australia - Hervey Bay" },
        { "HVN": "New Haven, CT, USA - Tweed New Haven" },
        { "HVR": "Havre, MT, USA - City County" },
        { "HWN": "Hwange National Park, Zimbabwe - Hwange National Park" },
        { "HYA": "Hyannis, MA, USA - Barnstable County" },
        { "HYD": "Hyderabad, India - Begumpet" },
        { "HYG": "Hydaburg, AK, USA" },
        { "HYS": "Hays, KS, USA - Hays Municipal Airport" },
        { "IAD": "Washington, DC, USA - Dulles" },
        { "IAD": "Washington, DC, USA - Washington-Dulles International" },
        { "IAH": "Houston, TX, USA - Houston Intercontinental" },
        { "IAH": "Houston, TX, USA - Houston Intercontinental" },
        { "IAS": "Iasi, Romania - Iasi" },
        { "IBZ": "Ibiza, Spain - Ibiza" },
        { "ICT": "Wichita, KS, USA - Mid-Continent Airport" },
        { "IDA": "Idaho Falls, ID, USA" },
        { "IEV": "Kiev, Ukraine - Zhulhany" },
        { "HIB": "Hibbing / Chisholm, MN, USA - Hibbing-Chisholm" },

        { "IFP": "Bullhead City, AZ, USA - Bullhead" },
        { "IGA": "Inagua, Bahamas" },
        { "IGM": "Kingman, AZ, USA - Mohave County" },
        { "IGR": "Iguazu, Misiones, Argentina - Iguazu International" },
        { "IGU": "Iguassu Falls, Parana, Brazil" },
        { "IJK": "Izhevsk, Russia" },
        { "IKT": "Irkutsk, Russia - Irkutsk" },
        { "ILE": "Killeen, TX, USA" },
        { "ILF": "Ilford, Manitoba, Canada" },
        { "ILI": "Iliamna, AK, USA" },
        { "ILM": "Wilmington, NC, USA - New Hanover County Airport" },
        { "ILO": "Iloilo, Philippines - Mandurriao" },
        { "ILQ": "Ilo, Moquegua, Peru - Ilo Airport" },
        { "ILY": "Islay, Scotland, United Kingdom - Glenegedale" },
        { "IMF": "Imphal, India - Municipal" },
        { "IMP": "Imperatriz, Maranhao, Brazil" },
        { "IMT": "Iron Mountain, MI, USA - Ford Airport" },
        { "IND": "Indianapolis, IN, USA - Indianapolis International Airport" },
        { "INL": "International Falls, MN, USA - Falls International" },
        { "INN": "Innsbruck, Austria - Kranebitten" },
        { "INT": "Winston-Salem, NC, USA - Smith Reynolds" },
        { "INU": "Nauru, Nauru" },
        { "INV": "Inverness, Scotland, United Kingdom - Inverness" },
        { "IOA": "Ioannina, Greece - Ioannina" },
        { "IOM": "Isle Of Man, Isle Of Man, United Kingdom - Ronaldsway" },
        { "IOS": "Ilheus, Bahia, Brazil - Eduardo Gomes" },
        { "IPC": "Easter Island, Chile - Mataveri" },
        { "IPH": "Ipoh, Malaysia - Ipoh" },
        { "IPI": "Ipiales, Colombia - San Luis" },
        { "IPT": "Williamsport, PA, USA - Williamsport Lycoming Municipal" },
        { "IQQ": "Iquique, Chile - Chucumata" },
        { "IQT": "Iquitos, Peru - Cf Secada" },
        { "ISB": "Islamabad, Pakistan - International" },
        { "ISC": "Isles Of Scilly, Isles Of Scilly, United Kingdom - Tresco" },
        { "ISN": "Williston, ND, USA - Sloulin Field International" },
        { "ISO": "Kinston, NC, USA" },
        { "ISP": "Islip, NY, USA - Long Island-Macarthur Airport" },
        { "IST": "Istanbul, Turkey - Ataturk" },
        { "ITH": "Ithaca, NY, USA - Tompkins County" },
        { "ITM": "Osaka, Japan - Itami International Was Osaka" },
        { "ITO": "Hilo, HI, USA - Hilo Hawaii:Hawaii-International Usa" },
        { "IWD": "Ironwood, MI, USA - Gogebic County Airport" },
        { "IXB": "Bagdogra, India - Bagdogra" },
        { "IXE": "Mangalore, India - Bajpe" },
        { "IXJ": "Jammu, India - Satwari" },
        { "IXM": "Madurai, India - Madurai" },
        { "IXU": "Aurangabad, India - Chikkalthana" },
        { "IXZ": "Port Blair, India - Port Blair" },
        { "IYK": "Inyokern, CA, USA - Inyokern Airport" },
        { "IZO": "Izumo, Japan" },
        { "JAC": "Jackson Hole, WY, USA - Jackson Hole Airport" },
        { "JAI": "Jaipur, India - Sanganeer" },
        { "JAN": "Jackson, MS, USA - Allen C Thompson Field" },
        { "JAT": "Jabat, Marshall Islands - Jabat Intl" },
        { "JAV": "Ilulissat, Greenland" },
        { "JAX": "Jacksonville, FL, USA - Jacksonville International Airport" },
        { "JBR": "Jonesboro, AR, USA - Municipal" },
        { "JCA": "Cannes, France - Mandelieu" },
        { "JDH": "Jodhpur, India" },
        { "JDP": "Paris, France - Issy Les Moulineaux" },
        { "JED": "Jeddah, Saudi Arabia - Jeddah International" },
        { "JER": "Jersey, Channel Islands, United Kingdom - States" },
        { "JFK": "New York, NY, USA - John F Kennedy Intl Airport" },
        { "JGA": "Jamnagar, India" },
        { "JHB": "Johor Bahru, Malaysia - Sultan Ismail International" },
        { "JHE": "Helsingborg, Sweden - Heliport" },
        { "JHM": "Kapalua, HI, USA - Kapalua" },
        { "JHW": "Jamestown, NY, USA - Chautauqua County Airport" },
        { "JIB": "Djibouti, Djibouti - Ambouli" },
        { "JKG": "Jonkoping, Sweden - Axamo" },
        { "JLN": "Joplin, MO, USA - Municipal Airport" },
        { "JMC": "Sausalito, CA, USA - Marin County" },
        { "JMK": "Mikonos, Greece - Mikonos" },
        { "JMM": "Malmo, Sweden - Malmo Harbour Heliport" },
        { "JMO": "Jomsom, Nepal" },
        { "JMS": "Jamestown, ND, USA - Jamestown Municipal Airport" },
        { "JNB": "Johannesburg, South Africa - Jan Smuts" },
        { "JNS": "Narssaq, Greenland" },
        { "JNU": "Juneau, AK, USA - Juneau" },
        { "JNX": "Naxos, Cyclades Islands, Greece - Naxos Airport" },

        { "JOG": "Yogyakarta, Indonesia" },
        { "JOI": "Joinville, Santa Catarina, Brazil - Federal" },
        { "JON": "Johnston Island, US, Outlying Islands" },
        { "JRA": "New York City, NY, USA" },
        { "JRO": "Kilimanjaro, Tanzania - Kilimanjaro" },
        { "JSI": "Skiathos, Greece - Skiathos" },
        { "JST": "Johnstown, PA, USA - Johnstown Cambria" },
        { "JTR": "Santorini/Thira Is, Greece - Santorini" },
        { "JUJ": "Jujuy, Provincia Jujuy, Argentina - El Cadillal" },
        { "JUL": "Juliaca, Peru - Juliaca" },
        { "KAB": "Kariba, Zimbabwe - Kariba" },
        { "KAE": "Kake, AK, USA" },
        { "KAL": "Kaltag, AK, USA" },
        { "KAN": "Kano, Nigeria - Aminu Kano International" },
        { "KAT": "Kaitaia, New Zealand - Kaitaia" },
        { "KBP": "Kiev, Ukraine - Borispol" },
        { "KBR": "Kota Bharu, Malaysia - Sultan Ismail Petra" },
        { "KCG": "Chignik, AK, USA - Fisheries" },
        { "KCH": "Kuching, Sarawak, Malaysia - Kuching" },
        { "KCL": "Chignik, AK, USA - Lagoon" },
        { "KEF": "Reykjavik, Iceland - Keflavik" },
        { "KEH": "Kenmore Air Harbor, WA, USA" },
        { "KEJ": "Kemerovo, Russia - Kemerovo" },
        { "KEL": "Kiel, Germany - Holtenau" },
        { "KEM": "Kemi/Tornio, Finland - Kemi" },
        { "KEP": "Nepalganj, Nepal - Nepalganj" },
        { "KER": "Kerman, Iran - Kerman" },
        { "KGC": "Kingscote, South Australia, Australia" },
        { "KGD": "Kaliningrad, Russia - Kaliningrad Airport" },
        { "KHH": "Kaohsiung, Taiwan" },
        { "KHI": "Karachi, Pakistan - Karachi" },
        { "KHV": "Khabarovsk, Russia - Novy" },
        { "KIN": "Kingston, Jamaica" },
        { "KIR": "Kerry County, Ireland - Kerry County" },
        { "KIV": "Kishinev, Moldova - Kishinev" },
        { "KIX": "Osaka, Japan - Kansai International" },
        { "KJA": "Krasnojarsk, Russia" },
        { "KKN": "Kirkenes, Norway - Hoeyburtmoen" },
        { "KLO": "Kalibo, Philippines - Kalibo" },
        { "KLR": "Kalmar, Sweden - Kalmar" },
        { "KLU": "Klagenfurt, Austria - Klagenfurt" },
        { "KLW": "Klawock, AK, USA" },
        { "KMG": "Kunming, China - Kunming" },
        { "KMI": "Miyazaki, Japan - Miyazaki" },
        { "KMJ": "Kumamoto, Japan - Kumamoto" },
        { "KNS": "King Island, Tasmania, Australia - King Island" },
        { "KOA": "Kona, HI, USA - Keahole" },
        { "KOI": "Kirkwall / Orkney Island, Scotland, United Kingdom - Kirkwall" },
        { "KOJ": "Kagoshima, Japan - Kagoshima" },
        { "KOK": "Kokkola/Pietarsaari, Finland - Kruunupyy" },
        { "KPN": "Kipnuk, AK, USA" },
        { "KPO": "Pohang, South Korea - Na" },
        { "KRF": "Kramfors, Sweden - Kramfors" },
        { "KRK": "Krakow, Poland - Balice" },
        { "KRN": "Kiruna, Sweden - Kiruna" },
        { "KRP": "Karup, Denmark - Karup" },
        { "KRR": "Krasnodar, Russia - Krasnodar" },
        { "KRS": "Kristiansand, Norway - Kjevik" },
        { "KRT": "Khartoum, Sudan - Civil" },
        { "KSA": "Kosrae, Caroline Islands, Micronesia" },
        { "KSC": "Kosice, Slovakia - Barca" },
        { "KSH": "Kermanshah, Iran - Bakhtaran Iran" },
        { "KSJ": "Kasos Island, Greece - Kasos Island" },
        { "KSU": "Kristiansund, Norway - Kvernberget" },
        { "KTM": "Kathmandu, Nepal - Tribhuvan" },
        { "KTN": "Ketchikan, AK, USA - Ketchikan International" },
        { "KTR": "Katherine, Northern Territory, Australia - Tindal" },
        { "KTW": "Katowice, Poland - Pyrzowice" },
        { "KUA": "Kuantan, Malaysia - Padang Geroda" },
        { "KUF": "Samara, Russia - Samara" },
        { "KUL": "Kuala Lumpur, Malaysia - Subang Kuala Lumpur International" },
        { "KUN": "Kaunas, Lithuania - Kaunas" },
        { "KUO": "Kuopio, Finland - Kuopio" },
        { "KUS": "Kulusuk, Greenland - Metropolitan Area" },
        { "KUV": "Kunsan, South Korea" },
        { "KVA": "Kavala, Greece - Kavala" },
        { "KWA": "Kwajalein, Marshall Islands" },
        { "KWI": "Kuwait, Kuwait - International" },
        { "KWL": "Guilin, China" },
        { "KZN": "Kazan, Russia - Kazan" },
        { "LAD": "Luanda, Angola - Fevereiro" },
        { "LAF": "Lafayette, IN, USA - Purdue University Airport" },
        { "LAN": "Lansing, MI, USA - Capital City Airport" },
        { "LAP": "La Paz, Baja California, Mexico - Aeropuerto General Marquez De Leon" },
        { "LAR": "Laramie, WY, USA - General Brees Field" },
        { "LAS": "Las Vegas, NV, USA - McCarran International Airport" },
        { "LAW": "Lawton, OK, USA - Municipal" },
        { "LAX": "Los Angeles, CA, USA - Los Angeles Intl Airport" },
        { "LAX": "Los Angeles, CA, USA - Los Angeles Intl Airport" },
        { "LBA": "Leeds/Bradford, England, United Kingdom" },
        { "LBB": "Lubbock, TX, USA - Lubbock International Airport" },
        { "LBE": "Latrobe, PA, USA - Westmoreland County" },
        { "LBF": "North Platte, NE, USA - Lee Bird Field" },
        { "LBL": "Liberal, KS, USA - Glenn L Martin Terminal" },
        { "LBU": "Labuan, Sabah, Malaysia" },
        { "LBV": "Libreville, Gabon - Libreville" },
        { "LCA": "Larnaca, Cyprus - Intl" },
        { "LCE": "La Ceiba, Honduras - International" },
        { "LCG": "La Coruna, Spain - La Coruna" },
        { "LCH": "Lake Charles, LA, USA - Municipal" },

        { "LCY": "London, England, United Kingdom - London City" },
        { "LDB": "Londrina, Parana, Brazil - Londrina" },
        { "LDE": "Lourdes/Tarbes, France - Tarbes International" },
        { "LDU": "Lahad Datu, Sabah, Malaysia - Lahad Datu" },
        { "LEA": "Learmonth, Western Australia, Australia" },
        { "LEB": "Lebanon/Hanover/White River, NH, USA - Lebanon Regional" },
        { "LED": "St Petersburg, Russia - Pulkovo" },
        { "LEH": "Le Havre, France - Le Havre" },
        { "LEI": "Almeria, Spain - Almeria" },
        { "LEJ": "Leipzig, Germany - Leipzig" },
        { "LET": "Leticia, Colombia - Gen Av Cob0" },
        { "LEX": "Lexington, KY, USA - Blue Grass Field" },
        { "LFT": "Lafayette / New Iberia, LA, USA - Municipal" },
        { "LFW": "Lome, Togo - Lome" },
        { "LGA": "New York, NY, USA - Laguardia" },
        { "LGB": "Long Beach, CA, USA - Long Beach Municipal Airport" },
        { "LGG": "Liege, Belgium - Bierset" },
        { "LGI": "Deadmans Cay / Long Island, Bahamas - Deadmans Cay" },
        { "LGK": "Langkawi, Malaysia" },
        { "LGP": "Legaspi, Philippines - Legaspi" },
        { "LGW": "London, England, United Kingdom - Gatwick" },
        { "LHE": "Lahore, Pakistan - Lahore" },
        { "LHR": "London, England, United Kingdom - Heathrow" },
        { "LIG": "Limoges, France - Bellegarde" },
        { "LIH": "Kauai Island, HI, USA - Lihue Municipal Airport" },
        { "LIM": "Lima, Peru - Intl Jorge Chavez" },
        { "LIN": "Milan, Italy - Linate" },
        { "LIR": "Liberia, Costa Rica - Liberia" },
        { "LIS": "Lisbon, Portugal - Lisboa" },
        { "LIT": "Little Rock, AR, USA - Little Rock Regional Airport" },
        { "LJU": "Ljubljana, Slovenia - Brnik" },
        { "LKE": "Seattle, WA, USA - Lake Union Sea Plane Base" },
        { "LKN": "Leknes, Norway - Leknes" },
        { "LKO": "Lucknow, India" },
        { "LLA": "Lulea, Sweden - Kallax" },
        { "LLW": "Lilongwe, Malawi - Kamuzu Intl" },
        { "LLY": "Mount Holly, NJ, USA - Mt Holly" },
        { "LMM": "Los Mochis, Sinaloa, Mexico" },
        { "LMN": "Limbang, Sarawak, Malaysia - Limbang" },
        { "LMT": "Klamath Falls, OR, USA - Kingsley Field Airport" },
        { "LNK": "Lincoln, NE, USA - Municipal Airport" },
        { "LNS": "Lancaster, PA, USA - Lancaster" },
        { "LNV": "Londolovit, Papua New Guinea - Londolovit" },
        { "LNY": "Lanai City, HI, USA - Lanai" },
        { "LNZ": "Linz, Austria - Linz" }

    ]




export default codeIATA;